"use client";
import { BriefcaseBusiness, Download, FileUp, Plus, Save, Sparkles } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import type { ClientAccount } from "@/lib/types";
import type { LinkedInAdsCampaign, LinkedInAdsReport, LinkedInAdsSummary } from "@/lib/linkedin-ads/types";

type Dashboard={report:LinkedInAdsReport;campaigns:LinkedInAdsCampaign[];summary:LinkedInAdsSummary;recommendations?:string[];demoMode:boolean};
const empty={campaignName:"",campaignGroup:"General",objective:"Lead Generation",status:"Active",budget:0,spend:0,impressions:0,clicks:0,conversions:0,leads:0,startDate:"",endDate:"",notes:""};
export function LinkedInAdsManagerApp({client}:{client:ClientAccount}){
 const[data,setData]=useState<Dashboard|null>(null),[notice,setNotice]=useState(""),[editing,setEditing]=useState(false),[campaign,setCampaign]=useState(empty),[notes,setNotes]=useState("");
 const admin=client.role==="admin",headers=useMemo(()=>({"x-beast-client-id":client.id,"x-beast-role":client.role}),[client.id,client.role]);
 useEffect(()=>{void load();/* eslint-disable-next-line react-hooks/exhaustive-deps */},[client.id]);
 async function load(){const r=await fetch("/api/linkedin-ads/summary",{headers});if(!r.ok)return setNotice("LinkedIn Ads report could not be loaded.");const d=await r.json() as Dashboard;setData(d);setNotes(d.report.notes);}
 async function add(e:FormEvent){e.preventDefault();const r=await fetch("/api/linkedin-ads/campaigns",{method:"POST",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify(campaign)});setNotice(r.ok?"LinkedIn campaign added.":"Campaign could not be added.");if(r.ok){setCampaign(empty);setEditing(false);await load();}}
 async function upload(file?:File){if(!file)return;const r=await fetch("/api/linkedin-ads/upload",{method:"POST",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify({fileName:file.name,csvData:await file.text()})});const x=await r.json() as {upload?:{rowsImported:number};error?:string};setNotice(r.ok?`CSV imported: ${x.upload?.rowsImported||0} campaigns.`:x.error||"CSV upload failed.");if(r.ok)await load();}
 async function save(){if(!data||data.demoMode)return setNotice("Create a manual report before saving notes.");const r=await fetch(`/api/linkedin-ads/reports/${data.report.id}`,{method:"PUT",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify({notes})});setNotice(r.ok?"LinkedIn report notes saved.":"Notes could not be saved.");}
 if(!data)return <div className="empty-state">Loading LinkedIn Ads performance...</div>;
 const recs=data.recommendations?.length?data.recommendations:["Upload LinkedIn campaign data to generate B2B performance recommendations."];
 return <div className="workspace-app-content linkedin-ads-app">
  <header className="linkedin-ads-header"><div className="linkedin-title"><BriefcaseBusiness size={24}/><div><p className="eyebrow">B2B advertising</p><h2>LinkedIn Ads Manager</h2><span>{data.report.dateRangeStart} to {data.report.dateRangeEnd} · Updated {date(data.report.updatedAt)}</span></div></div><div className="app-actions compact"><span className={`pill ${data.demoMode?"trial":"active"}`}>{data.demoMode?"Demo data":"Manual report"}</span><button className="ghost-button light" onClick={()=>setNotice("Export download is coming next.")} type="button"><Download size={15}/> Export</button>{admin&&<button className="button" onClick={()=>setEditing(true)} type="button"><Plus size={15}/> Add campaign</button>}</div></header>
  {notice&&<div className="notice">{notice}</div>}
  <div className="linkedin-metric-grid"><Metric l="Total spend" v={money(data.summary.totalSpend)}/><Metric l="Impressions" v={num(data.summary.totalImpressions)}/><Metric l="Clicks" v={num(data.summary.totalClicks)}/><Metric l="Conversions" v={num(data.summary.totalConversions)}/><Metric l="Leads" v={num(data.summary.totalLeads)}/><Metric l="CTR" v={`${data.summary.averageCtr.toFixed(2)}%`}/><Metric l="CPC" v={money(data.summary.averageCpc)}/><Metric l="CPL" v={money(data.summary.averageCpl)}/></div>
  <section className="mini-panel linkedin-campaign-panel"><div className="app-section-header"><div><p className="eyebrow">Campaign Performance</p><h3>{data.report.reportName}</h3></div>{admin&&<label className="ghost-button light linkedin-upload"><FileUp size={15}/> Upload CSV<input accept=".csv,text/csv" onChange={e=>upload(e.target.files?.[0])} type="file"/></label>}</div><div className="table-wrap embedded"><table className="client-table linkedin-campaign-table"><thead><tr><th>Campaign</th><th>Group</th><th>Objective</th><th>Status</th><th>Budget</th><th>Spend</th><th>Impressions</th><th>Clicks</th><th>Conversions</th><th>Leads</th><th>CTR</th><th>CPC</th><th>CPL</th></tr></thead><tbody>{data.campaigns.map(x=><tr key={x.id}><td><strong>{x.campaignName}</strong><small>{x.notes}</small></td><td>{x.campaignGroup}</td><td>{x.objective}</td><td><span className={`pill ${x.status.toLowerCase()}`}>{x.status}</span></td><td>{money(x.budget)}</td><td>{money(x.spend)}</td><td>{num(x.impressions)}</td><td>{num(x.clicks)}</td><td>{x.conversions}</td><td>{x.leads}</td><td>{x.ctr.toFixed(2)}%</td><td>{money(x.cpc)}</td><td>{money(x.cpl)}</td></tr>)}</tbody></table></div></section>
  <div className="app-grid linkedin-bottom-grid"><section className="mini-panel"><p className="eyebrow">Recommendations</p><h3>B2B audience and lead actions</h3><div className="recommendation-list">{recs.map(x=><div className="notice" key={x}><Sparkles size={14}/>{x}</div>)}</div></section><section className="mini-panel"><p className="eyebrow">B2B Audience Notes</p><h3>Report context</h3><textarea onChange={e=>setNotes(e.target.value)} readOnly={!admin} rows={7} value={notes}/>{admin&&<button className="ghost-button light" onClick={save} type="button"><Save size={15}/> Save notes</button>}</section><section className="mini-panel linkedin-api-card"><p className="eyebrow">Coming later</p><h3>Connect LinkedIn Marketing API</h3><p>Future version will connect LinkedIn ad accounts through LinkedIn OAuth and the LinkedIn Marketing API.</p><button disabled type="button">Connect LinkedIn Marketing API</button></section></div>
  {editing&&<form className="linkedin-campaign-form" onSubmit={add}><header><strong>Add manual LinkedIn campaign</strong><button onClick={()=>setEditing(false)} type="button">Close</button></header><div className="linkedin-form-grid">{Object.entries(campaign).map(([k,v])=>k==="notes"?<textarea key={k} onChange={e=>setCampaign(c=>({...c,notes:e.target.value}))} placeholder="Notes" value={String(v)}/>:<input key={k} onChange={e=>setCampaign(c=>({...c,[k]:typeof v==="number"?Number(e.target.value):e.target.value}))} placeholder={k.replace(/([A-Z])/g," $1")} type={typeof v==="number"?"number":k.includes("Date")?"date":"text"} value={v}/>)}</div><button className="button" type="submit">Save campaign</button></form>}
 </div>;
}
function Metric({l,v}:{l:string;v:string}){return <article className="report-metric-card"><span>{l}</span><strong>{v}</strong></article>;}function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(v);}function num(v:number){return v.toLocaleString("en-US");}function date(v:string){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(v));}
